{
  "builds": [
    {
      "file": "purevent2ha/Dockerfile",
      "build": {
        "args": {
          "BUILD_FROM": "ghcr.io/home-assistant/{arch}-base:3.11"
        }
      },
      "platforms": [
        "linux/amd64",
        "linux/arm/v7",
        "linux/arm/v6",
        "linux/arm64"
      ]
    }
  ]
}
